# Site settings
title: "Git Large File Storage"
description: "Git Large File Storage (LFS) replaces large files such as audio samples, videos, datasets, and graphics with text pointers inside Git, while storing the file contents on a remote server like GitHub.com or GitHub Enterprise."
git-lfs-release: 2.13.3

url: "https://git-lfs.github.com"

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-redirect-from

twitter:
  username: github

logo: /images/tweet-promo.png

exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE.txt
  - README.md
  - script
  - vendor/bundle/
